public enum Com {
	NEW_ONE_P_MAP,
    NEW_TWO_P_MAP,
    DRAW, 
    EXIT, 
    ARROW_DOWN, 
    ARROW_UP, 
    ARROW_LEFT, 
    ARROW_RIGHT, 
    S_DOWN,
    W_UP,
    A_LEFT,
    D_RIGHT,
    IDLE,
    SOLVE, 
}